namespace FreeServicesHub;

public partial class DataObjects
{
    // RegistrationKey - one-time use key generated by CI/CD pipeline
    public class RegistrationKey : ActionResponseObject
    {
        public Guid RegistrationKeyId { get; set; }
        public Guid TenantId { get; set; }
        public string KeyHash { get; set; } = string.Empty;      // SHA-256 hash, never store plaintext
        public string KeyPrefix { get; set; } = string.Empty;     // First 8 chars for identification
        public DateTime ExpiresAt { get; set; }
        public bool Used { get; set; }
        public Guid? UsedByAgentId { get; set; }
        public DateTime? UsedAt { get; set; }
        public DateTime Created { get; set; }
        public string CreatedBy { get; set; } = string.Empty;
        public string NewKeyPlaintext { get; set; } = string.Empty; // Transient - only populated on generation, never stored
    }

    // ApiClientToken - long-lived revocable token issued to agent during registration
    public class ApiClientToken : ActionResponseObject
    {
        public Guid ApiClientTokenId { get; set; }
        public Guid AgentId { get; set; }
        public Guid TenantId { get; set; }
        public string TokenHash { get; set; } = string.Empty;     // SHA-256 hash
        public string TokenPrefix { get; set; } = string.Empty;    // First 8 chars for identification
        public bool Active { get; set; } = true;
        public DateTime Created { get; set; }
        public DateTime? RevokedAt { get; set; }
        public string RevokedBy { get; set; } = string.Empty;
        public string AgentName { get; set; } = string.Empty;      // Denormalized for display
        public string NewTokenPlaintext { get; set; } = string.Empty; // Transient - only on generation
    }

    // AgentRegistrationRequest - what the agent sends to register
    public class AgentRegistrationRequest
    {
        public string RegistrationKey { get; set; } = string.Empty; // Plaintext key
        public string Hostname { get; set; } = string.Empty;
        public string OperatingSystem { get; set; } = string.Empty;
        public string Architecture { get; set; } = string.Empty;
        public string AgentVersion { get; set; } = string.Empty;
        public string DotNetVersion { get; set; } = string.Empty;
    }

    // AgentRegistrationResponse - what the hub returns after registration
    public class AgentRegistrationResponse : ActionResponseObject
    {
        public Guid AgentId { get; set; }
        public string ApiClientToken { get; set; } = string.Empty; // Plaintext token, shown once
        public string HubUrl { get; set; } = string.Empty;
    }

    // CiCdRegistrationResponse - returned by the CI/CD pipeline registration endpoint
    public class CiCdRegistrationResponse
    {
        public string AgentSlug { get; set; } = string.Empty;       // Friendly name / primary key for this agent
        public string RegistrationKey { get; set; } = string.Empty;  // Plaintext key to inject into agent appsettings.json
        public DateTime ExpiresAt { get; set; }                      // When the key expires
        public string Message { get; set; } = string.Empty;
    }
}
